[package]
name = "pic-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The image, operation and pipeline core for pic-cli"

[dependencies]
image.workspace = true
fast_image_resize.workspace = true
bytemuck.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
sha2.workspace = true
rustix.workspace = true
rustybuzz.workspace = true
ab_glyph.workspace = true
unicode-script.workspace = true

[lints]
workspace = true
